# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sitevisited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisited',
            old_name='words',
            new_name='inwords',
        ),
        migrations.AddField(
            model_name='sitevisited',
            name='outwords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
