# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161004_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisited',
            old_name='inwords',
            new_name='words',
        ),
        migrations.RemoveField(
            model_name='sitevisited',
            name='outwords',
        ),
    ]
