# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161004_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisited',
            name='inwords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
